title: Mike Logaciuk
markdown: kramdown

# basic setup
domain: mikelogaciuk.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://mikelogaciuk.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /REPOSITORY-NAME/           # place folder name if the site is served in a subfolder


# for atom feed
author:
  name: Mike Logaciuk
  email: mike.logaciuk@hotmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
