# https://github.com/actions/deploy-pages#usage
name: CI Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      # - run: npm install --save-dev @nuxt/test-utils vitest @vue/test-utils happy-dom playwright-core
      - run: npm run testci

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan for HIGH severity (non-failing)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          severity: "HIGH"
          exit-code: "0"
          format: "table"

      - name: Run Trivy filesystem scan for CRITICAL severity (failing)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          severity: "CRITICAL"
          exit-code: "1"
          format: "table"

      - name: Generate JSON report with CRITICAL and HIGH severity
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          severity: "CRITICAL,HIGH"
          exit-code: "0"
          format: "json"
          output: "trivy-report.json"

      - name: Upload Trivy report as an artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.json
