# https://github.com/actions/deploy-pages#usage
name: CI Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      # - run: npm install --save-dev @nuxt/test-utils vitest @vue/test-utils happy-dom playwright-core
      - run: npm run testci
